### ISSUE TITLE
Ideas for some improvements

### ISSUE THREAD

**Issue by AlessandroZ** [l4yton/js-parse#1]
Hi, 

I share some feedback about your tool because it seems really nice. I like the idea to have one tool to grep on API regex, parameters and endpoint at the same time. 

However it would be cool to be able to have some raw output (only one action will be called without no tab on the output) to automatise other actions using other tool. For example, without any parameters you could print all actions as you do right now and if we want only parameters, we can call it like that: 
```
js-parse -d domain.com -parameters > parameters.txt
```
And `parameters.txt` will contain our list of parameters without any needs to add a wrapper to parse the json output or the bash one. It would be easier to then use this file with other tools. 
Same think for API results and endpoints. 

Other important point is when you list endpoints, it would be nice to have all endpoints not only absolute ones. Relatives path could be really interesting. You could be inspired from `https://github.com/GerbenJavado/LinkFinder` regex which prints all path (relatives and absolute ones). Content types are printed as well (because they match the regex) you could remove it using some blacklist. 

These points could interest other persons, that why I share my points of view. 

Thanks for your work, have a nice day.

**Comment by AlessandroZ** [comment]
I forgot but my last point, in my opinion you should not ask for the domain with the `-d` parameter and grep for all path.

**Comment by l4yton** [comment]
Hey @AlessandroZ,

Thanks for your feedback, very much appreciated.

The first point is definitely a good idea and would make usage of the tool more flexible.
In regards to endpoints, it is already looking for relative and absolute paths. There is one regex for relative paths that matches something like `="/some/endpoint.php"` (maybe add `+"/some/endpoint.php` as regex) and another one that makes use of the domain that was provided to find absolute paths. The reason why I didn't want to have only one regex or copied the one of LinkFinder is on one hand that I didn't like the amount of false positives and garbage it returned (hence `-d` for better results) and on the other hand that Rust doesn't support all the nice regex features as for example python.

**Comment by AlessandroZ** [comment]
Ok I see, thanks for your response. 

I did some tests and you right, it retrieves relatives path as well.  Adding some space could give you some additional quotes but the result still works: 
```
var a= "/test.php" -> on your js file
```
Give an additional quote on the output.
```
Endpoints:
	"/test.php
```

If you have more than one space, it won't work, so I will add a `*` on your request to match multiple space or not. For example, this won't be found
```
var a=   "/test.php"
```

Thanks again for your work. Have a nice day.

**Comment by l4yton** [comment]
I have made a new branch that implements your suggestions, you can find it here: https://github.com/l4yton/js-parse/tree/issue-1
Let me know what you think and I will push it to master if everything is fine.

**Comment by AlessandroZ** [comment]
I have tested it and everything works well thanks a lot. 

If I was you, I would have left your first output with colors, all modules and tabs. Because it's nice and give you a brief presentation of all results found. Either when no options are called, you could launch everything or if it's complicated with rust, just adding a new options like `-all`. 

Anyway for me, everything is great. Thanks again.

**Comment by l4yton** [comment]
Awesome! I will add a `--all` option later and then merge it.
