### ISSUE TITLE
stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by AlessandroZ** [l4yton/js-parse#3]
Hi 

I had some issue parsing non utf8 file. 

Here is a simple js content which throw an error: 
```
//é
var a=1
```
And here the error message: 
```
$ js-parse -d aa -i . 
error: stream did not contain valid UTF-8
Subdomains:

Endpoints:

Parameters:

Headers:

API Keys:
```

**Comment by l4yton** [comment]
issue should be fixed now, can you confirm?

**Comment by AlessandroZ** [comment]
Works well now. Thanks a lot.
