### ISSUE TITLE
Adding in input a specific file

### ISSUE THREAD

**Issue by AlessandroZ** [l4yton/js-parse#4]
Hi, 

I'm trying to automate some things using js-parse and it would be awesome if except adding in input a directory we can give a file. I mean you could keep both option, just do a check if it's a directory or a file and depending on the type, you load one or multiple files: https://github.com/l4yton/js-parse/blob/master/src/main.rs#L57

For the user, nothing will change. 

Thanks a lot. 

Have a nice day.

**Comment by l4yton** [comment]
It should now be possible to specify a directory as well as a file as the input argument. Thanks for the suggestion :+1:
